[behaviors."dnb.kick".trigger]
rhythm = { type = "binary", op = "or", a = { type = "euclidean", steps = 16, pulses = 1, rotation = 0 }, b = { type = "euclidean", steps = 16, pulses = 1, rotation = 10 } }
probability = 1.0
[behaviors."dnb.kick".accent]
rhythm = { type = "euclidean", steps = 16, pulses = 1, rotation = 0 }
amount = 1.0
[behaviors."dnb.kick".profile]
base = 108
boost = 8
[behaviors."dnb.kick".output]
channel = 10
note = 36


[behaviors."dnb.snare".trigger]
rhythm = { type = "euclidean", steps = 16, pulses = 2, rotation = 4 }
probability = 1.0
[behaviors."dnb.snare".accent]
rhythm = { type = "euclidean", steps = 1, pulses = 0, rotation = 0 }
amount = 1.0
[behaviors."dnb.snare".profile]
base = 110
boost = 0
[behaviors."dnb.snare".output]
channel = 10
note = 38


[behaviors."dnb.closed_hat".trigger]
rhythm = { type = "binary", op = "a_not_b", a = { type = "euclidean", steps = 1, pulses = 1, rotation = 0 }, b = { type = "euclidean", steps = 16, pulses = 1, rotation = 14 } }
probability = 1.0
[behaviors."dnb.closed_hat".accent]
rhythm = { type = "euclidean", steps = 16, pulses = 8, rotation = 0 }
amount = 1.0
[behaviors."dnb.closed_hat".profile]
base = 48
boost = 24
[behaviors."dnb.closed_hat".output]
channel = 10
note = 42


[behaviors."dnb.open_hat".trigger]
rhythm = { type = "euclidean", steps = 16, pulses = 1, rotation = 14 }
probability = 1.0
[behaviors."dnb.open_hat".accent]
rhythm = { type = "euclidean", steps = 1, pulses = 0, rotation = 0 }
amount = 1.0
[behaviors."dnb.open_hat".profile]
base = 76
boost = 0
[behaviors."dnb.open_hat".output]
channel = 10
note = 46


[behaviors."dnb.rim".trigger]
rhythm = { type = "binary", op = "or", a = { type = "euclidean", steps = 16, pulses = 1, rotation = 7 }, b = { type = "euclidean", steps = 16, pulses = 1, rotation = 15 } }
probability = 0.65
[behaviors."dnb.rim".accent]
rhythm = { type = "euclidean", steps = 7, pulses = 2, rotation = 0 }
amount = 1.0
[behaviors."dnb.rim".profile]
base = 42
boost = 10
[behaviors."dnb.rim".output]
channel = 10
note = 37
